spring:
  security:
    oauth2:
      authorizationserver:
        issuer: 'http://authorization-server:8081'
        client:
          algashop-test-client:
            registration:
              client-id: algashop-test
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}test123"
              scopes:
                - products:read
                - products:write
                - products:stock:write
                - categories:read
                - categories:write
                - invoices:read
                - invoices:write
                - credit-cards:read
                - credit-cards:write
                - orders:read
                - orders:write
                - customers:read
                - customers:write
                - shopping-carts:read
                - shopping-carts:write
                - shipping-costs:preview
            token:
              access-token-time-to-live: 15m
              access-token-format: self-contained #reference
          algashop-ordering-service-client:
            registration:
              client-id: algashop-ordering-service
              authorization-grant-types:
                - client_credentials
              client-authentication-methods:
                - client_secret_basic
              client-secret: "{noop}secret123"
              scopes:
                - products:read
            token:
              access-token-time-to-live: 15m
              access-token-format: self-contained